"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./migration.module.css";

type Row={email:string;name:string;bubbleUserId:string;supabaseUserId:string|null;newAccountCreatedAt:string|null;migrationStatus:string;validationStatus:string;lastAttemptAt:string|null;lastError:string;received:number;processed:number};
type StripeRow={email:string;customerId:string;subscriptionId:string;subscriptionStatus:string;priceId:string;plan:string|null;companyId:string|null;companyName:string;companyCandidates:Array<{id:string;name:string}>;migrated:boolean;reason:string;eligible:boolean};
const label:Record<string,string>={missing_account:"Sem conta nova",not_started:"Pronto para preparar",running:"Em andamento",pending:"Pendente",retrying:"Tentando novamente",completed:"Dados copiados",failed:"Falhou"};
const stripeReason:Record<string,string>={ready:"Pronta para migrar",already_migrated:"Já migrada",missing_customer_email:"Cliente Stripe sem e-mail",inactive_subscription:"Assinatura inativa",unknown_price:"Preço/plano desconhecido",missing_company:"Sem empresa correspondente",ambiguous_company:"Mais de uma empresa correspondente",different_subscription_linked:"Empresa já vinculada a outra assinatura"};

export default function BubbleMigrationClient(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[nextCursor,setNextCursor]=useState<number|null>(null),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[busy,setBusy]=useState("");
 const[stripeRows,setStripeRows]=useState<StripeRow[]>([]),[stripeLoading,setStripeLoading]=useState(false),[stripeCursor,setStripeCursor]=useState<string|null>(null),[stripeHasMore,setStripeHasMore]=useState(false),[stripeBusy,setStripeBusy]=useState("");
 const requestPage=useCallback(async(cursor:number)=>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(`/api/admin/bubble-migration?limit=200&cursor=${cursor}`,{cache:"no-store",signal:controller.signal});const payload:any=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"Falha ao consultar o Bubble");return payload}finally{clearTimeout(timer)}},[]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const payload=await requestPage(0);setRows(payload.rows||[]);setNextCursor(typeof payload.nextCursor==="number"&&payload.nextCursor>0?payload.nextCursor:null)}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"A consulta ao Bubble demorou mais de 25 segundos. Tente atualizar novamente.":e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[requestPage]);
 async function loadMore(){if(nextCursor===null||loadingMore)return;setLoadingMore(true);setError("");try{const current=nextCursor;const payload=await requestPage(current);setRows(previous=>{const seen=new Set(previous.map(row=>row.bubbleUserId));return [...previous,...((payload.rows||[]) as Row[]).filter(row=>!seen.has(row.bubbleUserId))]});setNextCursor(typeof payload.nextCursor==="number"&&payload.nextCursor>current?payload.nextCursor:null)}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"A próxima página demorou mais de 25 segundos.":e instanceof Error?e.message:String(e))}finally{setLoadingMore(false)}}
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>rows.filter(r=>(filter==="all"||r.migrationStatus===filter)&&`${r.email} ${r.name}`.toLowerCase().includes(search.toLowerCase())),[rows,search,filter]);
 const totals=useMemo(()=>({all:rows.length,ready:rows.filter(r=>r.supabaseUserId).length,missing:rows.filter(r=>!r.supabaseUserId).length,done:rows.filter(r=>r.migrationStatus==="completed"&&r.validationStatus==="validated").length}),[rows]);
 async function prepare(row:Row){setBusy(row.email);setError("");try{const r=await fetch("/api/admin/bubble-migration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:row.email,bubbleUserId:row.bubbleUserId})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Falha ao preparar");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy("")}}
 async function migrateData(row:Row){
  if(!row.supabaseUserId)return;
  setBusy(row.email);setError("");
  try{
   const prepared=await fetch("/api/admin/bubble-migration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:row.email,bubbleUserId:row.bubbleUserId})});
   const preparedPayload:any=await prepared.json();
   if(!prepared.ok||!preparedPayload.ok)throw new Error(preparedPayload.error||"Falha ao preparar o vínculo");
   let migrationStatus="running";
   for(let attempt=0;attempt<80&&migrationStatus==="running";attempt++){
    const response=await fetch("/api/bubble-obj/migration/ensure",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({adminTargetUserId:row.supabaseUserId,callBudgetMs:20000,maxPages:10,maxTicks:5,processLimit:500,maxProcessTotal:1500})});
    const payload:any=await response.json();
    if(!response.ok||!payload.ok)throw new Error(payload.error||"Falha durante a cópia dos dados");
    migrationStatus=String(payload.status||"");
    if(migrationStatus==="failed")throw new Error("A cópia foi interrompida por erro. Consulte os detalhes da linha.");
   }
   if(migrationStatus!=="completed")throw new Error("A migração excedeu o limite seguro de retomadas. Execute novamente para continuar.");
   const validation=await fetch("/api/bubble-obj/migration/validate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({adminTargetUserId:row.supabaseUserId})});
   const validationPayload:any=await validation.json();
   if(!validation.ok||!validationPayload.ok)throw new Error(validationPayload.error||"Falha ao validar os dados copiados");
   if(validationPayload.status!=="validated")throw new Error("Os dados foram copiados, mas a auditoria encontrou divergências. A assinatura continua bloqueada.");
   await load();
  }catch(e){setError(e instanceof Error?e.message:String(e));await load()}finally{setBusy("")}
 }
 async function scanStripe(reset:boolean){if(stripeLoading)return;setStripeLoading(true);setError("");try{const cursor=reset?"":stripeCursor||"";const response=await fetch(`/api/admin/stripe-migration${cursor?`?starting_after=${encodeURIComponent(cursor)}`:""}`,{cache:"no-store"});const payload:any=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.detail||payload.error||"Falha ao consultar o Stripe");setStripeRows(previous=>reset?payload.rows||[]:[...previous,...(payload.rows||[])]);setStripeCursor(payload.nextCursor||null);setStripeHasMore(Boolean(payload.hasMore))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setStripeLoading(false)}}
 async function migrateStripe(row:StripeRow){if(!row.eligible||!row.companyId)return;setStripeBusy(row.subscriptionId);setError("");try{const response=await fetch("/api/admin/stripe-migration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:row.email,companyId:row.companyId,subscriptionId:row.subscriptionId})});const payload:any=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.detail||payload.error||"Falha ao migrar assinatura");setStripeRows(previous=>previous.map(item=>item.subscriptionId===row.subscriptionId?{...item,migrated:true,eligible:false,reason:"already_migrated"}:item))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setStripeBusy("")}}
 return <main className={styles.page}><header><div><small>ADMINISTRAÇÃO GLOBAL</small><h1>Migração completa do Bubble</h1><p>Inventário central dos usuários legados, vínculo com o Supabase e acompanhamento seguro da cópia dos dados.</p></div><button onClick={()=>void load()} disabled={loading}>{loading?"Atualizando…":"Atualizar Bubble"}</button></header>
 <div className={styles.cards}><article><span>Usuários encontrados</span><strong>{totals.all}</strong></article><article><span>Com conta no sistema novo</span><strong>{totals.ready}</strong></article><article><span>Precisam de conta/convite</span><strong>{totals.missing}</strong></article><article><span>Migrações validadas</span><strong>{totals.done}</strong></article></div>
 <section className={styles.notice}><b>Reconciliação segura de assinaturas</b><span>Consulta assinaturas já existentes no Stripe e vincula somente correspondências exatas de e-mail, empresa única e plano reconhecido. Não cria assinatura, não cobra e não sobrescreve outro vínculo.</span></section>
 <section className={styles.panel}><div className={styles.tools}><div><b>Assinaturas ainda não reconciliadas</b><small> Revise os bloqueios antes de aplicar.</small></div><button onClick={()=>void scanStripe(true)} disabled={stripeLoading}>{stripeLoading?"Consultando Stripe…":"Buscar assinaturas no Stripe"}</button></div>
 {stripeRows.length>0&&<div className={styles.table}><table><thead><tr><th>Cliente Stripe</th><th>Assinatura</th><th>Plano</th><th>Empresa</th><th>Diagnóstico</th><th>Ação</th></tr></thead><tbody>{stripeRows.map(r=><tr key={r.subscriptionId}><td><b>{r.email||"Sem e-mail"}</b><small>{r.customerId}</small></td><td><b>{r.subscriptionStatus}</b><small>{r.subscriptionId}</small></td><td>{r.plan||r.priceId||"—"}</td><td><b>{r.companyName||"—"}</b>{r.companyCandidates.length>1&&<small>{r.companyCandidates.map(c=>c.name).join(", ")}</small>}</td><td><span className={r.eligible?styles.ok:r.reason==="already_migrated"?styles.status:styles.blocked}>{stripeReason[r.reason]||r.reason}</span></td><td><button disabled={!r.eligible||stripeBusy===r.subscriptionId} onClick={()=>void migrateStripe(r)}>{stripeBusy===r.subscriptionId?"Migrando…":"Migrar assinatura"}</button></td></tr>)}</tbody></table>{stripeHasMore&&<div className={styles.more}><button onClick={()=>void scanStripe(false)} disabled={stripeLoading}>{stripeLoading?"Carregando…":"Carregar mais assinaturas"}</button></div>}</div>}</section>
 <section className={styles.notice}><b>Fluxo seguro em duas etapas</b><span>O administrador pode copiar e validar os dados sem acessar o e-mail do cliente. Esta ação não executa a finalização, não consulta o Stripe e mantém a conta sem assinatura até a revisão manual.</span></section>
 {error&&<div className={styles.error}>{error}</div>}<section className={styles.panel}><div className={styles.tools}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome ou e-mail"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os status</option><option value="missing_account">Sem conta nova</option><option value="not_started">Não iniciados</option><option value="running">Em andamento</option><option value="completed">Copiados</option><option value="failed">Com erro</option></select></div>
 <div className={styles.table}><table><thead><tr><th>Usuário do Bubble</th><th>Conta nova</th><th>Migração</th><th>Validação</th><th>Registros</th><th>Ação</th></tr></thead><tbody>{visible.map(r=><tr key={r.bubbleUserId}><td><b>{r.name||"Sem nome"}</b><small>{r.email}</small></td><td>{r.supabaseUserId?<><span className={styles.ok}>Vinculável</span><small>{r.newAccountCreatedAt?new Date(r.newAccountCreatedAt).toLocaleDateString("pt-BR"):""}</small></>:<span className={styles.blocked}>Criar/convocar conta</span>}</td><td><span className={styles.status}>{label[r.migrationStatus]||r.migrationStatus}</span>{r.lastError&&<small className={styles.rowError}>{r.lastError}</small>}</td><td>{r.validationStatus}</td><td>{r.processed}/{r.received}</td><td><button disabled={!r.supabaseUserId||busy===r.email||r.migrationStatus==="completed"} onClick={()=>void migrateData(r)}>{busy===r.email?"Migrando dados…":r.migrationStatus==="failed"?"Retomar migração":"Migrar dados"}</button></td></tr>)}</tbody></table>{!loading&&!visible.length&&<p className={styles.empty}>Nenhum usuário encontrado neste filtro.</p>}{loading&&<p className={styles.empty}>Consultando a primeira página de usuários do Bubble…</p>}{!loading&&nextCursor!==null&&<div className={styles.more}><button onClick={()=>void loadMore()} disabled={loadingMore}>{loadingMore?"Carregando…":"Carregar mais usuários"}</button></div>}</div></section></main>
}
