"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./migration.module.css";

type Row={email:string;name:string;bubbleUserId:string;supabaseUserId:string|null;newAccountCreatedAt:string|null;migrationStatus:string;validationStatus:string;lastAttemptAt:string|null;lastError:string;received:number;processed:number};
const label:Record<string,string>={missing_account:"Sem conta nova",not_started:"Pronto para preparar",running:"Em andamento",pending:"Pendente",retrying:"Tentando novamente",completed:"Dados copiados",failed:"Falhou"};
export default function BubbleMigrationClient(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[nextCursor,setNextCursor]=useState<number|null>(null),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[busy,setBusy]=useState("");
 const requestPage=useCallback(async(cursor:number)=>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(`/api/admin/bubble-migration?limit=200&cursor=${cursor}`,{cache:"no-store",signal:controller.signal});const payload:any=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"Falha ao consultar o Bubble");return payload}finally{clearTimeout(timer)}},[]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const payload=await requestPage(0);setRows(payload.rows||[]);setNextCursor(typeof payload.nextCursor==="number"&&payload.nextCursor>0?payload.nextCursor:null)}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"A consulta ao Bubble demorou mais de 25 segundos. Tente atualizar novamente.":e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[requestPage]);
 async function loadMore(){if(nextCursor===null||loadingMore)return;setLoadingMore(true);setError("");try{const current=nextCursor;const payload=await requestPage(current);setRows(previous=>{const seen=new Set(previous.map(row=>row.bubbleUserId));return [...previous,...((payload.rows||[]) as Row[]).filter(row=>!seen.has(row.bubbleUserId))]});setNextCursor(typeof payload.nextCursor==="number"&&payload.nextCursor>current?payload.nextCursor:null)}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"A próxima página demorou mais de 25 segundos.":e instanceof Error?e.message:String(e))}finally{setLoadingMore(false)}}
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>rows.filter(r=>(filter==="all"||r.migrationStatus===filter)&&`${r.email} ${r.name}`.toLowerCase().includes(search.toLowerCase())),[rows,search,filter]);
 const totals=useMemo(()=>({all:rows.length,ready:rows.filter(r=>r.supabaseUserId).length,missing:rows.filter(r=>!r.supabaseUserId).length,done:rows.filter(r=>r.migrationStatus==="completed"&&r.validationStatus==="validated").length}),[rows]);
 async function prepare(row:Row){setBusy(row.email);setError("");try{const r=await fetch("/api/admin/bubble-migration",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:row.email,bubbleUserId:row.bubbleUserId})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Falha ao preparar");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy("")}}
 return <main className={styles.page}><header><div><small>ADMINISTRAÇÃO GLOBAL</small><h1>Migração completa do Bubble</h1><p>Inventário central dos usuários legados, vínculo com o Supabase e acompanhamento seguro da cópia dos dados.</p></div><button onClick={()=>void load()} disabled={loading}>{loading?"Atualizando…":"Atualizar Bubble"}</button></header>
 <div className={styles.cards}><article><span>Usuários encontrados</span><strong>{totals.all}</strong></article><article><span>Com conta no sistema novo</span><strong>{totals.ready}</strong></article><article><span>Precisam de conta/convite</span><strong>{totals.missing}</strong></article><article><span>Migrações validadas</span><strong>{totals.done}</strong></article></div>
 <section className={styles.notice}><b>Fluxo seguro em duas etapas</b><span>Primeiro prepare o vínculo Bubble ↔ Supabase. Depois execute a migração pela conta vinculada; o sistema registra progresso, permite retomada e só conclui após auditoria.</span></section>
 {error&&<div className={styles.error}>{error}</div>}<section className={styles.panel}><div className={styles.tools}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar nome ou e-mail"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os status</option><option value="missing_account">Sem conta nova</option><option value="not_started">Não iniciados</option><option value="running">Em andamento</option><option value="completed">Copiados</option><option value="failed">Com erro</option></select></div>
 <div className={styles.table}><table><thead><tr><th>Usuário do Bubble</th><th>Conta nova</th><th>Migração</th><th>Validação</th><th>Registros</th><th>Ação</th></tr></thead><tbody>{visible.map(r=><tr key={r.bubbleUserId}><td><b>{r.name||"Sem nome"}</b><small>{r.email}</small></td><td>{r.supabaseUserId?<><span className={styles.ok}>Vinculável</span><small>{r.newAccountCreatedAt?new Date(r.newAccountCreatedAt).toLocaleDateString("pt-BR"):""}</small></>:<span className={styles.blocked}>Criar/convocar conta</span>}</td><td><span className={styles.status}>{label[r.migrationStatus]||r.migrationStatus}</span>{r.lastError&&<small className={styles.rowError}>{r.lastError}</small>}</td><td>{r.validationStatus}</td><td>{r.processed}/{r.received}</td><td><button disabled={!r.supabaseUserId||busy===r.email||r.migrationStatus!=="not_started"} onClick={()=>void prepare(r)}>{busy===r.email?"Preparando…":"Preparar vínculo"}</button></td></tr>)}</tbody></table>{!loading&&!visible.length&&<p className={styles.empty}>Nenhum usuário encontrado neste filtro.</p>}{loading&&<p className={styles.empty}>Consultando a primeira página de usuários do Bubble…</p>}{!loading&&nextCursor!==null&&<div className={styles.more}><button onClick={()=>void loadMore()} disabled={loadingMore}>{loadingMore?"Carregando…":"Carregar mais usuários"}</button></div>}</div></section></main>
}
