"use client";
import {useEffect,useMemo,useState} from "react";
import baseStyles from "../observabilidade/observabilidade.module.css";
import extraStyles from "../observabilidade/adminExtra.module.css";
const styles={...baseStyles,...extraStyles};
type User={id:string;email:string;company:string;plan:string;status:string;sessions:number;pageViews:number;errors:number;lastSeenAt:string|null;currentRoute:string;location:string;device:string};
export default function AdminUsersClient(){const[users,setUsers]=useState<User[]>([]);const[search,setSearch]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[accessing,setAccessing]=useState("");
 useEffect(()=>{fetch("/api/admin/observability?days=90",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.detail||j.error);setUsers(j.users||[])}).catch(e=>setError(String(e.message||e))).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return users.filter(u=>!q||`${u.email} ${u.company} ${u.plan} ${u.status}`.toLowerCase().includes(q))},[users,search]);
 function access(u:User){if(!u.email)return;setAccessing(u.id);const p=new URLSearchParams({email:u.email,userId:u.id,mode:"redirect"});window.location.href=`/api/admin/impersonate-link?${p.toString()}`}
 const active=users.filter(u=>u.status==="active").length;const recent=users.filter(u=>u.lastSeenAt&&Date.now()-new Date(u.lastSeenAt).getTime()<86400000).length;
 return <main className={styles.page}><header><div><small>ADMINISTRAÇÃO GLOBAL</small><h1>Acessar usuários</h1><p>Localize uma conta, confira seu contexto e entre com acesso administrativo seguro.</p></div></header>
 <div className={styles.accessSummary}><article><span>Contas cadastradas</span><strong>{users.length}</strong><small>usuários disponíveis no sistema</small></article><article><span>Assinaturas ativas</span><strong>{active}</strong><small>contas com status ativo</small></article><article><span>Acessaram hoje</span><strong>{recent}</strong><small>atividade nas últimas 24 horas</small></article></div>
 <section className={styles.securityNotice}><b>Acesso administrativo auditável</b><span>O sistema cria uma sessão temporária para suporte. Nenhuma senha do cliente é exibida ou alterada.</span></section>
 <section className={styles.panel}><div className={styles.heading}><div><h2>Diretório de usuários</h2><p>Pesquise por e-mail, empresa, plano ou situação da assinatura.</p></div><input className={styles.bigSearch} autoFocus placeholder="Digite o e-mail ou nome da empresa…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {error&&<div className={styles.error}>{error}</div>}{loading?<div className={styles.loadingBox}>Carregando contas…</div>:<div className={styles.userDirectory}>{filtered.map(u=><article key={u.id}><div className={styles.avatar}>{(u.email||"?").slice(0,1).toUpperCase()}</div><div className={styles.userIdentity}><b>{u.email||"Sem e-mail"}</b><span>{u.company}</span><small>{u.id}</small></div><div><span>Plano</span><b>{u.plan}</b><small className={u.status==="active"?styles.statusOk:styles.statusWarn}>{u.status}</small></div><div><span>Último acesso</span><b>{u.lastSeenAt?new Date(u.lastSeenAt).toLocaleString("pt-BR"):"Nunca"}</b><small>{u.location}</small></div><div><span>Uso</span><b>{u.sessions} sessões · {u.pageViews} views</b><small>{u.currentRoute}</small></div><button onClick={()=>access(u)} disabled={!u.email||!!accessing}>{accessing===u.id?"Acessando…":"Acessar conta →"}</button></article>)}</div>}
 {!loading&&!filtered.length&&<p className={styles.empty}>Nenhuma conta encontrada para essa busca.</p>}</section></main>}
