"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./observabilidade.module.css";
import extraBase from "./adminExtra.module.css";
import healthStyles from "./health.module.css";
const extra={...extraBase,...healthStyles};
import BrazilMap from "./BrazilMap";
type Pair={name:string;value:number};type User={id:string;email:string;company:string;plan:string;status:string;sessions:number;pageViews:number;errors:number;lastSeenAt:string|null;currentRoute:string;location:string;device:string};type Event={id:string;at:string;category:string;name:string;route:string;errorCode?:string;durationMs?:number};
type Data={generatedAt:string;metrics:Record<string,number>;daily:Array<{date:string;events:number;errors:number;users:number}>;users:User[];topRoutes:Pair[];topActions:Pair[];topErrors:Pair[];devices:Pair[];browsers:Pair[];locations:Pair[];states:Pair[];recent:Event[]};
export type AdminView="overview"|"geography"|"activity"|"errors";
const n=(v:number)=>new Intl.NumberFormat("pt-BR").format(Math.round(v||0));
function Bars({title,items}:{title:string;items:Pair[]}){const max=Math.max(1,...items.map(i=>i.value));return <section className={styles.panel}><h2>{title}</h2>{items.length?items.map(i=><div className={styles.barRow} key={i.name}><span title={i.name}>{i.name}</span><div><i style={{width:`${Math.max(3,i.value/max*100)}%`}}/></div><b>{n(i.value)}</b></div>):<p className={styles.muted}>Ainda sem dados.</p>}</section>}
function Chart({data}:{data:Data}){return <section className={styles.panel}><div className={styles.heading}><div><small>ENGAJAMENTO</small><h2>Atividade diária</h2><p>Eventos, usuários únicos e erros registrados.</p></div><span>Atualizado {new Date(data.generatedAt).toLocaleTimeString("pt-BR")}</span></div><div className={styles.chart}>{data.daily.map(d=>{const max=Math.max(1,...data.daily.map(x=>x.events));return <div key={d.date} title={`${d.events} eventos, ${d.users} usuários, ${d.errors} erros`}><div><i style={{height:`${Math.max(3,d.events/max*100)}%`}}/><em style={{height:`${Math.max(0,d.errors/max*100)}%`}}/></div><span>{d.date.slice(5)}</span></div>})}</div></section>}
function Feed({events}:{events:Event[]}){return <section className={styles.panel}><h2>Eventos recentes</h2><div className={styles.feed}>{events.slice(0,40).map(e=><div key={e.id}><span className={styles[e.category]||""}>{e.category}</span><b>{e.name}</b><code>{e.errorCode||e.route||"—"}</code><small>{new Date(e.at).toLocaleString("pt-BR")}</small></div>)}</div>{!events.length&&<p className={styles.muted}>Nenhum evento registrado neste período.</p>}</section>}
const titles={overview:["Saúde e uso do sistema","Resumo executivo de usuários, empresas, sessões e utilização."],geography:["Mapa e regiões","Distribuição geográfica das sessões, dispositivos e navegadores."],activity:["Atividade do sistema","Navegação, ações executadas e evolução diária de uso."],errors:["Erros e desempenho","Falhas recorrentes, taxa de erro e tempo médio de carregamento."]} as const;
export default function AdminObservabilityClient({view="overview"}:{view?:AdminView}){const[days,setDays]=useState(7);const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[search,setSearch]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/admin/observability?days=${days}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.detail||j.error||"Falha ao carregar");setData(j)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[days]);useEffect(()=>{void load();const id=setInterval(()=>void load(),60000);return()=>clearInterval(id)},[load]);const users=useMemo(()=>data?.users.filter(u=>`${u.email} ${u.company}`.toLowerCase().includes(search.toLowerCase())).slice(0,12)||[],[data,search]);const cards=data?[["Usuários",data.metrics.totalUsers],["Ativos agora",data.metrics.activeNow],["Ativos no período",data.metrics.activeUsers],["Empresas",data.metrics.companies],["Sessões",data.metrics.sessions],["Visualizações",data.metrics.pageViews],["Ações",data.metrics.actions],["Erros",data.metrics.errors]]:[];const title=titles[view];return <main className={styles.page}><header><div><small>ADMINISTRAÇÃO GLOBAL</small><h1>{title[0]}</h1><p>{title[1]}</p></div><div className={styles.controls}><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>24 horas</option><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option></select><button onClick={()=>void load()} disabled={loading}>{loading?"Atualizando…":"Atualizar"}</button></div></header>{error&&<div className={styles.error}><b>Não foi possível abrir o painel.</b><span>{error}</span></div>}
 {view==="overview"&&<><div className={styles.cards}>{cards.map(([label,value],index)=><article className={extra.metricCard} key={String(label)}><i>{["◎","●","↗","▦","◫","◇","＋","!"][index]}</i><span>{label}</span><strong>{n(Number(value))}</strong><small>{index===1?"nos últimos 5 minutos":"visão consolidada do período"}</small></article>)}</div>{data&&<><div className={styles.grid}><Bars title="Páginas mais acessadas" items={data.topRoutes}/><Bars title="Localização por país" items={data.locations}/><Bars title="Navegadores" items={data.browsers}/></div><section className={styles.panel}><div className={styles.heading}><div><h2>Usuários ativos recentemente</h2><p>Uma prévia das contas com atividade mais recente.</p></div><div className={extra.userTools}><input placeholder="Buscar usuário ou empresa" value={search} onChange={e=>setSearch(e.target.value)}/><Link href="/admin/usuarios">Ver todos →</Link></div></div><div className={styles.table}><table><thead><tr><th>Usuário</th><th>Empresa / plano</th><th>Última atividade</th><th>Página atual</th><th>Local</th><th>Sessões</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.email||"Sem e-mail"}</b></td><td>{u.company}<small>{u.plan} · {u.status}</small></td><td>{u.lastSeenAt?new Date(u.lastSeenAt).toLocaleString("pt-BR"):"—"}</td><td>{u.currentRoute}</td><td>{u.location}</td><td>{u.sessions}</td></tr>)}</tbody></table></div></section></>}</>}
 {view==="geography"&&data&&<><BrazilMap items={data.states||[]}/><div className={styles.grid}><Bars title="Países" items={data.locations}/><Bars title="Dispositivos" items={data.devices}/><Bars title="Navegadores" items={data.browsers}/></div></>}
 {view==="activity"&&data&&<><Chart data={data}/><div className={styles.grid}><Bars title="Páginas mais acessadas" items={data.topRoutes}/><Bars title="Ações mais usadas" items={data.topActions}/><Bars title="Dispositivos em uso" items={data.devices}/></div><Feed events={data.recent.filter(e=>e.category!=="error")}/></>}
 {view==="errors"&&data&&<><div className={extra.healthCards}><article><span>Erros no período</span><strong>{n(data.metrics.errors)}</strong></article><article><span>Taxa de erro</span><strong>{Number(data.metrics.errorRate||0).toFixed(2)}%</strong></article><article><span>Carregamento médio</span><strong>{n(data.metrics.avgLoadMs)} ms</strong></article></div><div className={styles.grid}><Bars title="Erros recorrentes" items={data.topErrors}/><Bars title="Rotas mais acessadas" items={data.topRoutes}/><Bars title="Navegadores" items={data.browsers}/></div><Feed events={data.recent.filter(e=>e.category==="error")}/></>}
 </main>}
