"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./observabilidade.module.css";
import extra from "./adminExtra.module.css";
import BrazilMap from "./BrazilMap";
type Pair={name:string;value:number}; type User={id:string;email:string;company:string;plan:string;status:string;sessions:number;pageViews:number;errors:number;lastSeenAt:string|null;currentRoute:string;location:string;device:string};
type Data={generatedAt:string;metrics:Record<string,number>;daily:Array<{date:string;events:number;errors:number;users:number}>;users:User[];topRoutes:Pair[];topActions:Pair[];topErrors:Pair[];devices:Pair[];browsers:Pair[];locations:Pair[];states:Pair[];recent:Array<any>};
const n=(v:number)=>new Intl.NumberFormat("pt-BR").format(Math.round(v||0));
function Bars({title,items}:{title:string;items:Pair[]}){const max=Math.max(1,...items.map(i=>i.value));return <section className={styles.panel}><h2>{title}</h2>{items.length?items.map(i=><div className={styles.barRow} key={i.name}><span title={i.name}>{i.name}</span><div><i style={{width:`${Math.max(3,i.value/max*100)}%`}}/></div><b>{n(i.value)}</b></div>):<p className={styles.muted}>Ainda sem dados.</p>}</section>}
export default function AdminObservabilityClient(){const[days,setDays]=useState(7);const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[search,setSearch]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/admin/observability?days=${days}`,{cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.detail||j.error||"Falha ao carregar");setData(j);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false)}},[days]);
 useEffect(()=>{void load();const id=setInterval(()=>void load(),60000);return()=>clearInterval(id)},[load]); const users=useMemo(()=>data?.users.filter(u=>`${u.email} ${u.company}`.toLowerCase().includes(search.toLowerCase()))??[],[data,search]);
 const cards=data?[['Usuários',data.metrics.totalUsers],['Ativos agora',data.metrics.activeNow],['Ativos no período',data.metrics.activeUsers],['Empresas',data.metrics.companies],['Sessões',data.metrics.sessions],['Visualizações',data.metrics.pageViews],['Ações',data.metrics.actions],['Erros',data.metrics.errors]]:[];
 return <main className={styles.page}><header><div><small>ADMINISTRAÇÃO GLOBAL</small><h1>Saúde e uso do sistema</h1><p>Usuários, atividade, falhas, desempenho, dispositivos e localização aproximada.</p></div><div className={styles.controls}><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>24 horas</option><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option></select><button onClick={()=>void load()} disabled={loading}>{loading?'Atualizando…':'Atualizar'}</button></div></header>
 {error&&<div className={styles.error}><b>Não foi possível abrir o painel.</b><span>{error}</span>{error.includes('schema')&&<span>Execute a migration 20260826000000_admin_observability.sql no Supabase.</span>}</div>}
 <div className={styles.cards}>{cards.map(([label,value],index)=><article className={extra.metricCard} key={String(label)}><i>{['◎','●','↗','▦','◫','◇','＋','!'][index]}</i><span>{label}</span><strong>{n(Number(value))}</strong><small>{index===1?'nos últimos 5 minutos':index===7?'eventos que exigem atenção':'visão consolidada do período'}</small></article>)}</div>
 {data&&<><section id="atividade" className={styles.panel}><div className={styles.heading}><div><small>ENGAJAMENTO</small><h2>Atividade diária</h2><p>Eventos, usuários únicos e erros.</p></div><span>Atualizado {new Date(data.generatedAt).toLocaleTimeString('pt-BR')}</span></div><div className={styles.chart}>{data.daily.map(d=>{const max=Math.max(1,...data.daily.map(x=>x.events));return <div key={d.date} title={`${d.date}: ${d.events} eventos, ${d.users} usuários, ${d.errors} erros`}><div><i style={{height:`${Math.max(3,d.events/max*100)}%`}}/><em style={{height:`${Math.max(0,d.errors/max*100)}%`}}/></div><span>{d.date.slice(5)}</span></div>})}</div></section>
 <BrazilMap items={data.states||[]}/>
 <div className={styles.grid}><Bars title="Páginas mais acessadas" items={data.topRoutes}/><Bars title="Ações mais usadas" items={data.topActions}/><Bars title="Erros recorrentes" items={data.topErrors}/><Bars title="Dispositivos" items={data.devices}/><Bars title="Navegadores" items={data.browsers}/><Bars title="Países" items={data.locations}/></div>
 <section className={styles.panel}><div className={styles.heading}><div><h2>Usuários</h2><p>Último acesso, empresa, plano, localização e atividade.</p></div><div className={extra.userTools}><input placeholder="Buscar usuário ou empresa" value={search} onChange={e=>setSearch(e.target.value)}/><a href="/admin/usuarios">Acessar contas →</a></div></div><div className={styles.table}><table><thead><tr><th>Usuário</th><th>Empresa / plano</th><th>Última atividade</th><th>Página atual</th><th>Dispositivo / local</th><th>Sessões</th><th>Views</th><th>Erros</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.email||'Sem e-mail'}</b><small>{u.id}</small></td><td>{u.company}<small>{u.plan} · {u.status}</small></td><td>{u.lastSeenAt?new Date(u.lastSeenAt).toLocaleString('pt-BR'):'—'}</td><td>{u.currentRoute}</td><td>{u.device}<small>{u.location}</small></td><td>{u.sessions}</td><td>{u.pageViews}</td><td className={u.errors?styles.danger:''}>{u.errors}</td></tr>)}</tbody></table></div></section>
 <section className={styles.panel}><h2>Eventos recentes</h2><div className={styles.feed}>{data.recent.slice(0,30).map(e=><div key={e.id}><span className={styles[e.category]||''}>{e.category}</span><b>{e.name}</b><code>{e.route||'—'}</code><small>{new Date(e.at).toLocaleString('pt-BR')}</small></div>)}</div></section></>}
</main>}
