"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./observabilidade.module.css";
import extraBase from "./adminExtra.module.css";
import mapStyles from "./realMap.module.css";
const extra={...extraBase,...mapStyles};
type Pair={name:string;value:number};type Feature={properties:Record<string,unknown>;geometry:{type:"Polygon"|"MultiPolygon";coordinates:number[][][]|number[][][][]}};
const aliases:Record<string,string>={"sao paulo":"SP","rio de janeiro":"RJ","minas gerais":"MG","rio grande do sul":"RS","santa catarina":"SC","parana":"PR","bahia":"BA","goias":"GO","distrito federal":"DF","ceara":"CE","pernambuco":"PE","espirito santo":"ES","mato grosso":"MT","mato grosso do sul":"MS","para":"PA","amazonas":"AM","rio grande do norte":"RN","paraiba":"PB","maranhao":"MA","piaui":"PI","tocantins":"TO","rondonia":"RO","roraima":"RR","amapa":"AP","acre":"AC","alagoas":"AL","sergipe":"SE"};
const ibgeCodes:Record<string,string>={"11":"RO","12":"AC","13":"AM","14":"RR","15":"PA","16":"AP","17":"TO","21":"MA","22":"PI","23":"CE","24":"RN","25":"PB","26":"PE","27":"AL","28":"SE","29":"BA","31":"MG","32":"ES","33":"RJ","35":"SP","41":"PR","42":"SC","43":"RS","50":"MS","51":"MT","52":"GO","53":"DF"};
function normalize(value:string){const raw=value.trim();if(raw.length===2)return raw.toUpperCase();return aliases[raw.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()]||raw.toUpperCase()}
function ufOf(f:Feature){const p=f.properties;const raw=String(p.sigla||p.UF||p.uf||p.codarea||p.nome||"");return ibgeCodes[raw]||raw}
const project=([lon,lat]:number[])=>[(lon+74)*11.2,(6-lat)*10.2];
function ringPath(ring:number[][]){return ring.map((point,index)=>{const[x,y]=project(point);return `${index?"L":"M"}${x.toFixed(1)} ${y.toFixed(1)}`}).join(" ")+" Z"}
function featurePath(feature:Feature){const c=feature.geometry.coordinates;return feature.geometry.type==="Polygon"?(c as number[][][]).map(ringPath).join(" "):(c as number[][][][]).flatMap(poly=>poly.map(ringPath)).join(" ")}
export default function BrazilMap({items}:{items:Pair[]}){const[features,setFeatures]=useState<Feature[]>([]);const[failed,setFailed]=useState(false);useEffect(()=>{fetch("/api/admin/brazil-map").then(async r=>{if(!r.ok)throw new Error("map");const j=await r.json();setFeatures(j.features||[])}).catch(()=>setFailed(true))},[]);const values=useMemo(()=>new Map(items.map(i=>[normalize(i.name),i.value])),[items]);const max=Math.max(1,...items.map(i=>i.value));const total=items.reduce((s,i)=>s+i.value,0);return <section className={`${styles.panel} ${extra.mapPanel}`}><div className={styles.heading}><div><small>DISTRIBUIÇÃO GEOGRÁFICA</small><h2>Presença de usuários no Brasil</h2><p>Mapa estadual oficial do IBGE com sessões localizadas no período.</p></div><div className={extra.mapTotal}><strong>{total}</strong><span>sessões localizadas</span></div></div><div className={extra.mapLayout}><div className={extra.realMap}>{features.length?<svg viewBox="0 0 510 470" role="img" aria-label="Mapa do Brasil dividido por estados">{features.map((f,index)=>{const uf=normalize(ufOf(f));const value=values.get(uf)||0;return <path key={`${uf}-${index}`} d={featurePath(f)} style={{fill:value?`rgba(0,184,117,${.22+.68*value/max})`:"#e8f2ef"}}><title>{uf}: {value} sessões</title></path>})}</svg>:<div className={extra.mapLoading}>{failed?"Não foi possível carregar a malha do IBGE.":"Carregando mapa oficial…"}</div>}<div className={extra.mapLegend}><span>Menor atividade</span><i/><i/><i/><span>Maior atividade</span></div></div><div className={extra.stateList}><h3>Estados com mais sessões</h3>{items.slice(0,10).map((i,index)=><div key={i.name}><span><i>{index+1}</i>{normalize(i.name)}</span><b>{i.value}</b></div>)}{!items.length&&<p className={styles.muted}>As regiões aparecerão conforme novas sessões forem registradas.</p>}</div></div></section>}
