import {NextRequest,NextResponse} from "next/server";
import {getSupabaseAdmin} from "../../../lib/supabaseAdmin";
import {requireSystemAdmin} from "../../../lib/systemAdmin";

export const runtime="nodejs";
export const dynamic="force-dynamic";

async function listAuthUsers(db:ReturnType<typeof getSupabaseAdmin>){const users:Array<Record<string,string|null>>=[];for(let page=1;page<=20;page++){const{data,error}=await db.auth.admin.listUsers({page,perPage:1000});if(error)throw error;for(const user of data.users)users.push({id:user.id,email:user.email??null,created_at:user.created_at??null,last_sign_in_at:user.last_sign_in_at??null,banned_until:String((user as any).banned_until||"")||null});if(data.users.length<1000)break}return users}

export async function GET(req:NextRequest){try{const auth=await requireSystemAdmin(req);if(!auth.ok)return NextResponse.json({ok:false,error:auth.error},{status:auth.status});const db=getSupabaseAdmin();const[authUsers,mapResult,companiesResult,membersResult]=await Promise.all([listAuthUsers(db),db.from("bubble_obj_user_map").select("bubble_user_id,email,nome,supabase_user_id"),db.from("companies").select("id,fantasy_name,email"),db.from("company_members").select("user_id,company_id")]);if(mapResult.error)throw mapResult.error;const companies=companiesResult.data??[];const members=membersResult.data??[];const companyById=new Map(companies.map((company:any)=>[String(company.id),{id:String(company.id),name:String(company.fantasy_name||"Sem nome")}])) ;const companiesByUser=new Map<string,Array<{id:string;name:string}>>();for(const member of members as any[]){const company=companyById.get(String(member.user_id?member.company_id:""));if(!company)continue;const key=String(member.user_id);companiesByUser.set(key,[...(companiesByUser.get(key)||[]),company])}const companiesByEmail=new Map(companies.filter((company:any)=>company.email).map((company:any)=>[String(company.email).trim().toLowerCase(),[{id:String(company.id),name:String(company.fantasy_name||"Sem nome")}]]));const seen=new Set<string>();const legacyUsers=[];for(const row of mapResult.data??[]){const email=String((row as any).email||"").trim().toLowerCase();if(!email||seen.has(email))continue;seen.add(email);const userId=String((row as any).supabase_user_id||"");legacyUsers.push({email,authUserId:userId||null,companies:companiesByUser.get(userId)||companiesByEmail.get(email)||[],companiesCount:(companiesByUser.get(userId)||companiesByEmail.get(email)||[]).length})}return NextResponse.json({ok:true,authUsers,legacyUsers},{headers:{"cache-control":"private, max-age=30, stale-while-revalidate=120"}})}catch(error){return NextResponse.json({ok:false,error:"registrations_load_failed",detail:error instanceof Error?error.message:String(error)},{status:500})}}
